name: linter-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run install
        run: npm ci

      - name: linter project check
        run: npx eslint .