name: linter-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run install
        run: make install

      - name: linter project check
        run: make lint

      - name: run tests
        run: make test
